/* ============================================================
   Static itinerary data: places, events, months, routes
   Rich per-event dossiers live in data/events/<id>.json
   ============================================================ */

window.PLACES = {
  zurich:      { name: 'Zürich',        lat: 47.3769, lon: 8.5417,  type: 'home' },
  lucerne:     { name: 'Lucerne',       lat: 47.0502, lon: 8.3093,  type: 'city' },
  bunol:       { name: 'Buñol',         lat: 39.4204, lon: -0.7903, type: 'city' },
  munich:      { name: 'Munich',        lat: 48.1351, lon: 11.5820, type: 'city' },
  alba:        { name: 'Alba',          lat: 44.7009, lon: 8.0353,  type: 'city' },
  bern:        { name: 'Bern',          lat: 46.9480, lon: 7.4474,  type: 'city' },
  charmey:     { name: 'Charmey',       lat: 46.6194, lon: 7.1633,  type: 'city' },
  vienna:      { name: 'Vienna',        lat: 48.2082, lon: 16.3738, type: 'city' },
  strasbourg:  { name: 'Strasbourg',    lat: 48.5734, lon: 7.7521,  type: 'city' },
  milan:       { name: 'Milan',         lat: 45.4642, lon: 9.1900,  type: 'city' },
  stmoritz:    { name: 'St. Moritz',    lat: 46.4983, lon: 9.8380,  type: 'city' },
  venice:      { name: 'Venice',        lat: 45.4408, lon: 12.3155, type: 'city' },
  basel:       { name: 'Basel',         lat: 47.5596, lon: 7.5886,  type: 'city' },
  nice:        { name: 'Nice',          lat: 43.7102, lon: 7.2620,  type: 'airport' },
  dublin:      { name: 'Dublin',        lat: 53.3498, lon: -6.2603, type: 'city' },
  valencia:    { name: 'Valencia',      lat: 39.4699, lon: -0.3763, type: 'city' },
  seville:     { name: 'Seville',       lat: 37.3891, lon: -5.9845, type: 'city' },
  amsterdam:   { name: 'Amsterdam',     lat: 52.3676, lon: 4.9041,  type: 'city' },
  lisse:       { name: 'Lisse',         lat: 52.2708, lon: 4.5462,  type: 'city' },
  cannes:      { name: 'Cannes',        lat: 43.5528, lon: 7.0174,  type: 'city' },
  monaco:      { name: 'Monaco',        lat: 43.7384, lon: 7.4246,  type: 'city' },
  glastonbury: { name: 'Pilton',        lat: 51.1550, lon: -2.5850, type: 'city' },
  edinburgh:   { name: 'Edinburgh',     lat: 55.9533, lon: -3.1883, type: 'city' },
  london:      { name: 'London',        lat: 51.5072, lon: -0.1276, type: 'city' },
  pamplona:    { name: 'Pamplona',      lat: 42.8125, lon: -1.6458, type: 'city' },
  siena:       { name: 'Siena',         lat: 43.3188, lon: 11.3308, type: 'city' },
};

/* Every clickable event. `place` keys into PLACES. */
window.EVENTS = [
  { id: 'lucerne-festival',    name: 'Lucerne Festival',            place: 'lucerne',    month: 'Aug 2026', kind: 'arts' },
  { id: 'la-tomatina',         name: 'La Tomatina',                 place: 'bunol',      month: 'Aug 2026', kind: 'festival' },
  { id: 'oktoberfest',         name: 'Oktoberfest',                 place: 'munich',     month: 'Sep 2026', kind: 'festival' },
  { id: 'desalpe',             name: 'Désalpe — Alpine Cow Parade', place: 'charmey',    month: 'Sep 2026', kind: 'festival' },
  { id: 'alba-truffle',        name: 'Alba White Truffle Fair',     place: 'alba',       month: 'Oct 2026', kind: 'food' },
  { id: 'bern-zibelemaerit',   name: 'Zibelemärit',                 place: 'bern',       month: 'Nov 2026', kind: 'festival' },
  { id: 'vienna-christmas',    name: 'Vienna Christmas Markets',    place: 'vienna',     month: 'Nov 2026', kind: 'festival' },
  { id: 'strasbourg-christmas',name: 'Strasbourg Christmas Market', place: 'strasbourg', month: 'Dec 2026', kind: 'festival' },
  { id: 'la-scala',            name: 'La Scala Opening Night',      place: 'milan',      month: 'Dec 2026', kind: 'arts' },
  { id: 'white-turf',          name: 'White Turf St. Moritz',       place: 'stmoritz',   month: 'Jan 2027', kind: 'sport' },
  { id: 'venice-carnival',     name: 'Carnevale di Venezia',        place: 'venice',     month: 'Feb 2027', kind: 'festival' },
  { id: 'basel-fasnacht',      name: 'Basler Fasnacht',             place: 'basel',      month: 'Feb 2027', kind: 'festival' },
  { id: 'nice-carnival',       name: 'Carnaval de Nice',            place: 'nice',       month: 'Feb 2027', kind: 'festival' },
  { id: 'st-patricks',         name: "St. Patrick's Festival",      place: 'dublin',     month: 'Mar 2027', kind: 'festival' },
  { id: 'las-fallas',          name: 'Las Fallas',                  place: 'valencia',   month: 'Mar 2027', kind: 'festival' },
  { id: 'semana-santa',        name: 'Semana Santa',                place: 'seville',    month: 'Mar 2027', kind: 'festival' },
  { id: 'keukenhof',           name: "Keukenhof & King's Day",      place: 'amsterdam',  month: 'Apr 2027', kind: 'festival' },
  { id: 'sechselaeuten',       name: 'Sechseläuten',                place: 'zurich',     month: 'Apr 2027', kind: 'festival' },
  { id: 'cannes-film',         name: 'Cannes Film Festival',        place: 'cannes',     month: 'May 2027', kind: 'arts' },
  { id: 'monaco-gp',           name: 'Monaco Grand Prix',           place: 'monaco',     month: 'Jun 2027', kind: 'sport' },
  { id: 'glastonbury',         name: 'Glastonbury Festival',        place: 'glastonbury',month: 'Jun 2027', kind: 'festival' },
  { id: 'tour-de-france',      name: 'Tour de France Grand Départ', place: 'edinburgh',  month: 'Jul 2027', kind: 'sport' },
  { id: 'wimbledon',           name: 'Wimbledon',                   place: 'london',     month: 'Jul 2027', kind: 'sport' },
  { id: 'san-fermin',          name: 'San Fermín',                  place: 'pamplona',   month: 'Jul 2027', kind: 'festival' },
  { id: 'palio-siena',         name: 'Palio di Siena',              place: 'siena',      month: 'Aug 2027', kind: 'sport' },
  { id: 'edinburgh-fringe',    name: 'Edinburgh Festival Fringe',   place: 'edinburgh',  month: 'Aug 2027', kind: 'arts' },
  { id: 'street-parade',       name: 'Zürich Street Parade',        place: 'zurich',     month: 'Aug 2027', kind: 'festival' },
];

/* Month-by-month calendar. headline/alts reference EVENTS ids. */
window.MONTHS = [
  { key: '2026-08', label: 'August', year: '2026', season: 'autumn', note: 'settle in', badge: 'Ease in',
    headline: 'lucerne-festival', alts: ['la-tomatina'],
    desc: 'You move in Aug 9 — keep month one light. World-class classical music an hour away, then one bold trip if you\'re up for it. La Tomatina (Buñol, Aug 26) is the wild-card bucket-list option.',
    chips: [{ t: 'home', v: 'Lucerne by train' }, { t: 'cost', v: '€60 local / €350+ Tomatina' }, { t: 'travel', v: 'Rail, or fly 2h' }],
    extraAlts: ['Salzburg Festival — opera summit, through Aug 30 (4h train)', 'Notting Hill Carnival — London, Aug 30–31 (free)', 'F1 Dutch GP — Zandvoort, Aug 21–23'] },
  { key: '2026-09', label: 'September', year: '2026', season: 'autumn', badge: 'Headline',
    headline: 'oktoberfest', alts: ['desalpe'],
    desc: 'The original and the biggest — a definitive European rite. Entry is free; a tent table reservation is the splurge (book months ahead). At home, the Désalpe cow parades bring flower-crowned herds down from the alps.',
    chips: [{ t: 'travel', v: 'Rail 3h30' }, { t: 'cost', v: '€400–900 (tent = more)' }, { t: 'book', v: 'Book tent now' }],
    extraAlts: ['Venice Film Festival — red carpets, Sep 2–12', 'F1 Italian GP, Monza — the Tifosi temple, Sep 4–6', 'Swiss wine harvest — Neuchâtel/Lutry, late Sep'] },
  { key: '2026-10', label: 'October', year: '2026', season: 'autumn', badge: 'Food',
    headline: 'alba-truffle', alts: [],
    desc: 'The global capital of the white truffle, wrapped in Barolo wine country — the year\'s great gourmet pilgrimage. Pair the market with a Langhe wine day.',
    chips: [{ t: 'travel', v: 'Fly 1h / rail 5–6h' }, { t: 'cost', v: '€450–750' }, { t: 'home', v: 'Basel Herbstmesse option' }],
    extraAlts: ['Basel Herbstmesse — Switzerland\'s oldest funfair, from Oct 24', 'Frankfurt Book Fair — world\'s biggest, Oct 7–11', 'Berlin Festival of Lights — projection art, early Oct (free)'] },
  { key: '2026-11', label: 'November', year: '2026', season: 'winter', badge: 'Season opens',
    headline: 'bern-zibelemaerit', alts: ['vienna-christmas'],
    desc: 'Beat the December crowds: Vienna\'s Rathausplatz market opens first, and Bern\'s 600-year-old dawn Onion Market (Nov 30) is a short train away. A cosy, low-cost month.',
    chips: [{ t: 'home', v: 'Bern 1h by rail' }, { t: 'travel', v: 'Fly or rail' }, { t: 'cost', v: '€250–500' }],
    extraAlts: ['Autumn rugby internationals — Twickenham/Paris/Dublin', 'Bonfire Night — Lewes/London, Nov 5 (very British)', 'Nuremberg Christkindlesmarkt — the iconic one, from Nov 27'] },
  { key: '2026-12', label: 'December', year: '2026', season: 'winter', badge: 'Headline',
    headline: 'strasbourg-christmas', alts: ['la-scala'],
    desc: 'Peak market season — Strasbourg ("Capital of Christmas," 3h train) and fairytale Prague. For a glamour night, La Scala\'s Dec 7 season premiere is opera\'s most storied evening (or watch the free piazza broadcast).',
    chips: [{ t: 'home', v: 'Zürich markets at home' }, { t: 'travel', v: 'Rail 3h Strasbourg' }, { t: 'cost', v: '€200–600' }],
    extraAlts: ['Zurich & Basel markets — on the doorstep', 'Colmar / Munich / Cologne markets — all easy', 'Vienna — market + imperial city break'] },
  { key: '2027-01', label: 'January', year: '2027', season: 'winter', note: 'recharge', badge: 'Quiet month',
    headline: 'white-turf', alts: ['venice-carnival'],
    desc: 'Europe\'s event calendar is genuinely quiet in January — a good month to explore Switzerland and save. White Turf horse racing on frozen St. Moritz lake, or catch Venice Carnival\'s opening water parade at month\'s end.',
    chips: [{ t: 'home', v: 'Swiss Alps at home' }, { t: 'cost', v: '€150–450' }, { t: 'travel', v: 'Local rail' }],
    extraAlts: ['Vienna Ball Season — imperial waltz nights', 'Swiss ski culture — home turf, low travel cost'] },
  { key: '2027-02', label: 'February', year: '2027', season: 'winter', badge: 'Headline, at home',
    headline: 'basel-fasnacht', alts: ['venice-carnival', 'nice-carnival'],
    desc: 'Carnival month, and the best one is basically at home: UNESCO-listed Basel Fasnacht plunges the city into lantern-lit darkness at 4am. Bookend it with Venice\'s masks (through Feb 9) or Nice\'s flower-battle parades.',
    chips: [{ t: 'home', v: 'Basel 55 min by rail' }, { t: 'cost', v: '€40 local / €400 Venice' }, { t: 'travel', v: 'Rail or fly' }],
    extraAlts: ['Six Nations rugby — Feb weekends across Europe', 'Cologne Karneval — Germany\'s biggest, ~Feb 8'] },
  { key: '2027-03', label: 'March', year: '2027', season: 'spring', badge: 'Big choice',
    headline: 'st-patricks', alts: ['las-fallas', 'semana-santa'],
    desc: 'Three icons, take your pick (or two if you cluster). Dublin for the global home of St. Paddy\'s; Valencia for the fire-and-firecracker Fallas; Seville for the spellbinding Holy Week processions.',
    chips: [{ t: 'travel', v: 'Fly 2–2.5h' }, { t: 'cost', v: '€400–700' }, { t: 'book', v: 'Dublin books up' }],
    cluster: 'Fallas (mid-March) → stay south → Semana Santa (late March) on one Spain trip.',
    extraAlts: ['Six Nations finale — title weekend, mid-Mar'] },
  { key: '2027-04', label: 'April', year: '2027', season: 'spring', badge: 'Headline',
    headline: 'keukenhof', alts: ['sechselaeuten'],
    desc: 'Time one Netherlands trip to hit peak tulips at Keukenhof and the country-wide orange street party of King\'s Day. At home, Zürich\'s own Sechseläuten (Apr 19) burns the Böögg to predict summer.',
    chips: [{ t: 'home', v: 'Zürich, Apr 19' }, { t: 'travel', v: 'Fly 1h30' }, { t: 'cost', v: '€400–650' }],
    cluster: 'Base in Amsterdam a few days — tulips + city + King\'s Day in one flight.',
    extraAlts: ['Feria de Abril — Seville fair, flamenco & sherry, ~Apr 18–24', 'Bonn cherry blossoms — pink tunnel, mid-Apr'] },
  { key: '2027-05', label: 'May', year: '2027', season: 'summer', badge: 'Blockbuster',
    headline: 'cannes-film', alts: [],
    desc: 'Cinema\'s most glamorous fortnight. Screenings are industry-only, but the Croisette buzz, beach cinema and star-spotting are free. Thrifty tip: base in Nice and day-trip to dodge Cannes hotel spikes.',
    chips: [{ t: 'travel', v: 'Fly 1h30 + train' }, { t: 'cost', v: '€500–900' }, { t: 'book', v: 'Riviera hotels early' }],
    cluster: 'Cannes\' afterglow flows straight into June\'s Monaco GP — one long Riviera trip covers both.',
    extraAlts: ['Eurovision — mid-May (or free viewing parties)', 'Giro d\'Italia — mountain stages, free roadside'] },
  { key: '2027-06', label: 'June', year: '2027', season: 'summer', badge: 'Headline',
    headline: 'monaco-gp', alts: ['glastonbury'],
    desc: 'F1\'s crown jewel — glamour, harbour, the most famous street circuit in sport. Grandstands are pricey; general-admission "rail" spots and the Nice base are the smart plays.',
    chips: [{ t: 'travel', v: 'Fly 1h30 + train' }, { t: 'cost', v: '€600–1,200' }, { t: 'book', v: 'Book GP + Glastonbury now' }],
    extraAlts: ['Champions League Final — Madrid, Jun 5', 'Primavera Sound — Barcelona, Jun 3–5', 'Wimbledon — begins Jun 28'] },
  { key: '2027-07', label: 'July', year: '2027', season: 'summer', badge: 'Headline',
    headline: 'tour-de-france', alts: ['wimbledon', 'san-fermin', 'palio-siena'],
    desc: 'A rare historic UK start makes 2027 special — and roadside viewing is free and electric. Pair with Wimbledon for a UK week, or swap for Spain\'s adrenaline classic.',
    chips: [{ t: 'travel', v: 'Fly 2h' }, { t: 'cost', v: '€500–950' }, { t: 'book', v: 'Peak season' }],
    cluster: 'UK July = Tour de France start + Wimbledon in one trip. Book San Fermín lodging 3–4 months out (huge spike).',
    extraAlts: ['Bordeaux Fête le Vin — biennial wine fest, Jul 7–11', 'Tomorrowland — Belgium EDM, mid-late Jul (sells out)'] },
  { key: '2027-08', label: 'August', year: '2027', season: 'summer', note: 'finale', badge: 'Grand finale',
    headline: 'edinburgh-fringe', alts: ['palio-siena', 'street-parade', 'la-tomatina'],
    desc: 'End on the biggest arts festival on earth — the whole city becomes a stage, many shows free or pay-what-you-want. Then close the year with a home-turf party or one last Italian/Spanish icon.',
    chips: [{ t: 'home', v: 'Zürich, Aug 14' }, { t: 'travel', v: 'Fly 2h' }, { t: 'cost', v: '€500–800' }],
    extraAlts: ['Notting Hill Carnival — London, Aug 29–30 (free)'] },
];

/* Multi-leg routes for the map. Each stop: { place, eventId?, label, month }.
   Leg mode applies to the leg LEAVING that stop: 'rail' | 'fly' | 'drive'. */
window.ROUTES = [
  {
    id: 'greatest-hits', name: 'The Greatest Hits', color: '#a4543a', accent: '#c98a6e',
    tag: 'Recommended · Balanced', price: '~€8,500–11,000 / yr',
    blurb: 'One marquee event per month, the definitive version — normal hotels, economy flights, booked ahead.',
    bullets: ['~12–14 trips, one headline each', 'Mid-range stays, cabin-bag flights', 'Splurge only on 2–3 signature nights'],
    stops: [
      { place: 'zurich', label: 'Home base', month: 'Aug 9, 2026', mode: 'rail' },
      { place: 'lucerne', eventId: 'lucerne-festival', month: 'Aug 2026', mode: 'rail' },
      { place: 'munich', eventId: 'oktoberfest', month: 'Sep 2026', mode: 'fly' },
      { place: 'alba', eventId: 'alba-truffle', month: 'Oct 2026', mode: 'rail' },
      { place: 'bern', eventId: 'bern-zibelemaerit', month: 'Nov 2026', mode: 'rail' },
      { place: 'strasbourg', eventId: 'strasbourg-christmas', month: 'Dec 2026', mode: 'rail' },
      { place: 'milan', eventId: 'la-scala', month: 'Dec 7, 2026', mode: 'rail' },
      { place: 'stmoritz', eventId: 'white-turf', month: 'Jan–Feb 2027', mode: 'rail' },
      { place: 'basel', eventId: 'basel-fasnacht', month: 'Feb 2027', mode: 'fly' },
      { place: 'dublin', eventId: 'st-patricks', month: 'Mar 2027', mode: 'fly' },
      { place: 'amsterdam', eventId: 'keukenhof', month: 'Apr 2027', mode: 'fly' },
      { place: 'cannes', eventId: 'cannes-film', month: 'May 2027', mode: 'rail' },
      { place: 'monaco', eventId: 'monaco-gp', month: 'Jun 2027', mode: 'fly' },
      { place: 'edinburgh', eventId: 'edinburgh-fringe', month: 'Jul–Aug 2027', mode: 'fly' },
      { place: 'zurich', eventId: 'street-parade', month: 'Aug 2027', mode: null },
    ],
  },
  {
    id: 'thrifty', name: 'The Thrifty Route', color: '#6f7a4e', accent: '#a3ad7e',
    tag: 'Budget-Max · Same spirit, less spend', price: '~€4,500–6,500 / yr',
    blurb: 'Free, at-home and rail-reachable events; far trips clustered into one; Basel/easyJet mid-week; hostels & aparthotels.',
    bullets: ['Free events: Fasnacht, carnivals, roadside cycling, markets', 'Rail + Half-Fare card; Nightjet saves hotel nights', '2–3 destinations per flight (clustering)'],
    stops: [
      { place: 'zurich', label: 'Home base', month: 'Aug 9, 2026', mode: 'rail' },
      { place: 'lucerne', eventId: 'lucerne-festival', month: 'Aug 2026', mode: 'rail' },
      { place: 'munich', eventId: 'oktoberfest', month: 'Sep 2026 (day trip)', mode: 'rail' },
      { place: 'bern', eventId: 'bern-zibelemaerit', month: 'Nov 2026', mode: 'rail' },
      { place: 'strasbourg', eventId: 'strasbourg-christmas', month: 'Dec 2026', mode: 'rail' },
      { place: 'milan', eventId: 'la-scala', month: 'Dec 2026 (piazza screen)', mode: 'rail' },
      { place: 'basel', eventId: 'basel-fasnacht', month: 'Feb 2027 (free)', mode: 'fly' },
      { place: 'valencia', eventId: 'las-fallas', month: 'Mar 2027', mode: 'fly' },
      { place: 'seville', eventId: 'semana-santa', month: 'Mar 2027 (one Spain trip)', mode: 'fly' },
      { place: 'zurich', eventId: 'sechselaeuten', month: 'Apr 2027 (free)', mode: 'fly' },
      { place: 'nice', eventId: 'cannes-film', month: 'May 2027 (Nice base)', mode: 'fly' },
      { place: 'siena', eventId: 'palio-siena', month: 'Jul 2027 (free)', mode: 'rail' },
      { place: 'zurich', eventId: 'street-parade', month: 'Aug 2027 (free)', mode: null },
    ],
  },
  {
    id: 'bucket-list', name: 'The Bucket-List', color: '#44607a', accent: '#7e97ad',
    tag: 'Splurge · Once-in-a-lifetime', price: '~€14,000–20,000 / yr',
    blurb: 'The events worth the money and the early booking: a tent table, a grandstand, the Croisette, the Pyramid Stage.',
    bullets: ['Premium tickets & grandstands', 'Central hotels in peak weeks', 'Book 3–6 months ahead (some sell out in minutes)'],
    stops: [
      { place: 'zurich', label: 'Home base', month: 'Aug 9, 2026', mode: 'fly' },
      { place: 'bunol', eventId: 'la-tomatina', month: 'Aug 26, 2026', mode: 'fly' },
      { place: 'munich', eventId: 'oktoberfest', month: 'Sep 2026 (tent table)', mode: 'rail' },
      { place: 'milan', eventId: 'la-scala', month: 'Dec 7, 2026 (premiere)', mode: 'rail' },
      { place: 'venice', eventId: 'venice-carnival', month: 'Feb 2027 (masked ball)', mode: 'fly' },
      { place: 'dublin', eventId: 'st-patricks', month: 'Mar 2027', mode: 'fly' },
      { place: 'amsterdam', eventId: 'keukenhof', month: 'Apr 2027', mode: 'fly' },
      { place: 'cannes', eventId: 'cannes-film', month: 'May 2027 (Croisette)', mode: 'rail' },
      { place: 'monaco', eventId: 'monaco-gp', month: 'Jun 2027 (grandstand)', mode: 'fly' },
      { place: 'glastonbury', eventId: 'glastonbury', month: 'Jun 23–27, 2027', mode: 'drive' },
      { place: 'london', eventId: 'wimbledon', month: 'Jul 2027 (Centre Court)', mode: 'fly' },
      { place: 'pamplona', eventId: 'san-fermin', month: 'Jul 6–14, 2027', mode: 'fly' },
      { place: 'edinburgh', eventId: 'edinburgh-fringe', month: 'Aug 2027', mode: 'fly' },
      { place: 'zurich', label: 'Home', month: 'Aug 2027', mode: null },
    ],
  },
];

window.BOOK_EARLY = [
  { event: 'Oktoberfest tent reservation', id: 'oktoberfest', when: 'Sep 2026', why: 'Tables book out months ahead; hotels 2–4× normal' },
  { event: 'La Scala opening night', id: 'la-scala', when: 'Dec 7, 2026', why: 'Premiere tickets famously scarce & pricey' },
  { event: 'Cannes Riviera hotels', id: 'cannes-film', when: 'May 2027', why: 'Nice/Cannes lodging extreme in mid-May' },
  { event: 'Monaco Grand Prix', id: 'monaco-gp', when: 'Jun 4–6, 2027', why: 'Grandstands go early; whole region fills' },
  { event: 'Glastonbury', id: 'glastonbury', when: 'Jun 23–27, 2027', why: 'Registration essential; sells out in minutes' },
  { event: 'San Fermín lodging', id: 'san-fermin', when: 'Jul 6–14, 2027', why: 'Pamplona region spikes hard; base in San Sebastián' },
  { event: 'Wimbledon', id: 'wimbledon', when: 'late Jun 2027', why: 'Ballot/queue system; plan the route in' },
];

window.CLUSTERS = [
  { name: 'Riviera (May–Jun)', desc: 'Cannes afterglow → Monaco GP → Nice base. One flight, three highlights.' },
  { name: 'Spain spring (Mar)', desc: 'Las Fallas (Valencia) → Semana Santa (Seville). Cheap internal hops.' },
  { name: 'Netherlands (Apr)', desc: 'Keukenhof tulips + Amsterdam + King\'s Day in one long weekend.' },
  { name: 'UK July', desc: 'Tour de France Edinburgh start + Wimbledon.' },
  { name: 'Italian rail line', desc: 'Milan + Como + Venice all sit on one train route from Zürich.' },
];

window.SAVINGS = [
  { name: 'Fly from Basel (BSL)', desc: 'easyJet\'s biggest continental base — usually cheaper than ZRH for Spain, Portugal, Eastern Europe. ~1h15 from Zürich.' },
  { name: 'Buy the Half-Fare travelcard (~CHF 190/yr)', desc: '50% off Swiss fares + the Swiss leg of international tickets. Pays for itself fast.' },
  { name: 'Book the exact train early', desc: 'SBB Supersaver & DB Sparpreis open ~3 months out (Milan from ~€29, Munich from ~€22).' },
  { name: 'Nightjet sleepers', desc: 'Vienna and Berlin overnight — saves a hotel night.' },
  { name: 'Fly Tue/Wed, cabin-bag only', desc: 'Pay bags online in advance; book short-haul 6–8 weeks ahead.' },
];

/* Concrete date spans for the wall-calendar view (from researched dossiers;
   summer-2027 patterns marked expected in the dossiers). [start, end] inclusive. */
window.CAL_DATES = {
  'lucerne-festival':     [['2026-08-13', '2026-09-13']],
  'la-tomatina':          [['2026-08-26', '2026-08-26']],
  'oktoberfest':          [['2026-09-19', '2026-10-04']],
  'desalpe':              [['2026-09-26', '2026-09-26'], ['2026-10-03', '2026-10-03']],
  'alba-truffle':         [['2026-10-10', '2026-12-06']],
  'vienna-christmas':     [['2026-11-13', '2026-12-26']],
  'bern-zibelemaerit':    [['2026-11-23', '2026-11-23']],
  'strasbourg-christmas': [['2026-11-26', '2026-12-24']],
  'la-scala':             [['2026-12-07', '2026-12-07']],
  'venice-carnival':      [['2027-01-23', '2027-02-09']],
  'white-turf':           [['2027-02-07', '2027-02-07'], ['2027-02-14', '2027-02-14'], ['2027-02-21', '2027-02-21']],
  'nice-carnival':        [['2027-02-09', '2027-02-28']],
  'basel-fasnacht':       [['2027-02-15', '2027-02-17']],
  'st-patricks':          [['2027-03-13', '2027-03-17']],
  'las-fallas':           [['2027-03-15', '2027-03-19']],
  'semana-santa':         [['2027-03-21', '2027-03-28']],
  'keukenhof':            [['2027-03-25', '2027-05-16']],
  'sechselaeuten':        [['2027-04-19', '2027-04-19']],
  'cannes-film':          [['2027-05-11', '2027-05-22']],
  'monaco-gp':            [['2027-06-04', '2027-06-06']],
  'glastonbury':          [['2027-06-23', '2027-06-27']],
  'wimbledon':            [['2027-06-28', '2027-07-11']],
  'tour-de-france':       [['2027-07-02', '2027-07-04']],
  'san-fermin':           [['2027-07-06', '2027-07-14']],
  'palio-siena':          [['2027-07-02', '2027-07-02'], ['2027-08-16', '2027-08-16']],
  'edinburgh-fringe':     [['2027-08-06', '2027-08-30']],
  'street-parade':        [['2027-08-14', '2027-08-14']],
};

/* Distinct colors for calendar spans & builder (muted, print-like) */
window.EVENT_COLORS = ['#9c4b2f', '#6c7352', '#3f5b70', '#8a6d3b', '#71575f', '#4e6e66'];
